### ISSUE TITLE
Contacting the developer. About the work of ModAPI Launcher without the Internet and the inability to start the game. Spore with ModAPI Launcher without an Internet connection.

### ISSUE THREAD

**Issue by dir512** [emd4600/Spore-ModAPI#47] opened 2023-07-18 18:14 UTC
I appeal to you as a competent person who is well versed with the mods and the technical part of the Spore game, could you make it so that the ModAPI Launcher no longer requires an Internet connection to run the game with it, so that it works offline mode?

Many creators with mods in Spore from various countries are interested in this issue, who could at least try to figure it out.

It just turns out such a problem that without the Internet, the game with ModAPI requires a connection to read the mods and does not start, and you can only start it through the emergency mod testing mode in Sporemodder FX.

And even then, half of the mods that work with ModAPI will stop being read and work, and creations will be distorted to the level of those that could be created with mods that can work without ModAPI - for example, parts of Pandora Toolbox and of Drone Parts, enlarged with UPE, and distort creations, are compressed and creatures made with Drone parts turn into a bunch of cubes scattered across fantastic planes

This is corrected by reupload PNG, if you go into a regular game with ModAPI, but if you upload it to a game launched in this way bypassing ModAPI, then again the creations are displayed as distorted

And when the Internet comes off for technical reasons or there is no way to use it, I want to be able to continue playing Spore as with mods that did not require ModAPI, which asks for an Internet connection to start the game.

This is a very serious shortcoming of the ModAPI launcher and the .sporemod system files, because before it was just a .package that I threw into a folder and it will always work

Went offline - The whole game will be impossible to start.

So, I don't want to launch everything in an emergency way through testing mods in Sporemodder FX, and then align and redo all the creations distorted by the fact that UPE stopped working.

I still hope that in the next versions of ModAPI they will wean off the Internet connection to run the game (not to update the client, the Internet is required to update the client)

Best regards, JimReinor, one of the mod creators from the Russian language mod creator site Spore.cr

**Comment by VanillaCold** [comment] 2023-11-19 19:44
It's actually a glitch caused by the update-checking code; it fails when there's no connection, but the exception does not get caught and so the game crashes.

Until the issue is fixed in the Spore ModAPI Launcher Kit, I'd recommend using the Spore Mod Loader instead; it still uses the Spore ModAPI Core DLLs - and by extension is compatible with all mods - but does not have the same issue as far as I'm aware.
(https://github.com/Rosalie241/SporeModLoader)

**Comment by dir512** [comment] 2023-11-20 07:35
Thanks for the answer about the Spore ModAPI Launcher Kit.

Best regards, JimReinor.

**Comment by emd4600** [comment] 2024-11-04 18:36
The issue has been fixed.

**Closed by emd4600** 2024-11-04 18:36 UTC
